include:
  - workspaces/libs/docker-compose.yml
  - workspaces/data/docker-compose.yml
  - workspaces/worker/docker-compose.yml

services:
  data:
    # the depends_on does not seem to work with include
    depends_on:
      - libs

  worker:
    # the depends_on does not seem to work with include
    depends_on:
      - data
      - libs
