hoist: false
hoistWorkspacePackages: false
sharedWorkspaceLockfile: false
packages:
  - "workspaces/data/"
  - "workspaces/libs/"
  - "workspaces/infra/"
  - "workspaces/kube/"
  - "workspaces/worker/"
