# settings

set dotenv-load
set quiet

# env
export PATH := "./node_modules/.bin:" + env('PATH')

# imports
mod app 'justfile.app'
mod image 'justfile.image'
mod manifest 'justfile.manifest'
mod secret 'justfile.secret'

# variables
src:='src/'

# tasks

dev:
  concurrently -c auto 'just check --watch --preserveWatchOutput' 'just serve'

serve:
  tsx --watch --env-file=.env src/main.ts

start:
  node dist/main.js

check *args:
  tsc --noEmit --pretty {{args}}

alias type-check := check

type-cover:
	type-coverage --detail --strict --ignore-catch --at-least 100

build *args:
  rm -rf dist/
  tsc -p tsconfig.build.json

lint *args:
  eslint {{src}} {{args}}

fmt:
	eslint --fix {{src}}

test *args:
  vitest run {{args}}

test-debug *args:
  just test -c vitest.debug.config.ts {{args}}

e2e *args:
  just test -c vite.e2e.config.ts {{args}}
