# settings
set dotenv-load
set quiet

# env
export PATH := "./node_modules/.bin:" + env('PATH')

# variables
src:='src/'

# tasks

[parallel]
dev: (_pre "check" "check --watch --preserveWatchOutput") (_pre "test" "test --watch")

check *args:
  tsc --noEmit --pretty {{args}}

alias type-check := check

type-cover:
  type-coverage --detail --strict --ignore-catch --at-least 100

build *args:
  tsdown {{args}}

lint *args:
  eslint {{src}} {{args}}

fmt:
  eslint --fix {{src}}

test *args:
  vitest run {{args}}

test-debug *args:
  just test -c vitest.debug.config.ts {{args}}

# helpers

_pre prefix cmd:
  #!/usr/bin/env bash
  just {{cmd}} 2>&1 | sed "s/^/[{{prefix}}] /"
