classes: {
  app: {
    style: {
      fill: darkorange
    }
  }
  load_balancer: {
    style: {
      fill: gold
    }
  }
  device: {
    style: {
      fill: silver
    }
  }
  bdd: {
    shape: cylinder
    style: {
      fill: deepskyblue
    }
  }
  pkg: {
    shape: package
    style: {
      fill: silver
    }
  }
}
